Feature/storeis
Godden13/Rebase_FaceBook_Clone pull request #29
Opened 2023-05-30 12:04 UTC by MALWICK

2023-05-30 12:18 UTC, kadjialan requested changes

2023-05-30 12:18 UTC, kadjialan commented on src/Components/Atoms.tsx
could create  a folder for atoms inside  which you could create a file for react icons for better separation of concerne

2023-05-30 12:18 UTC, kadjialan commented on src/app/modal/FeedCard.tsx
why join  the styling with the code when you can create them in your components an import them

2023-05-30 12:18 UTC, kadjialan commented on src/app/modal/Postbox.tsx
styles join together with code

2023-05-30 12:18 UTC, kadjialan commented on src/app/modal/Stories.tsx
what is the need for this file?

2023-05-30 13:10 UTC, MALWICK commented on src/Components/Atoms.tsx
i did create a folder for atoms and a file for iconatoms.jsx

2023-05-30 13:11 UTC, MALWICK commented on src/app/modal/FeedCard.tsx
i have exported the styling they are no more in our files

2023-05-30 13:11 UTC, MALWICK commented on src/app/modal/Postbox.tsx
i have separated the styling

2023-05-30 13:11 UTC, MALWICK commented on src/app/modal/Stories.tsx
i deleted those unwanted icons

2023-05-30 13:17 UTC, kadjialan submitted a review, later dismissed

2023-05-31 09:25 UTC, kadjialan requested changes

2023-05-31 09:25 UTC, kadjialan commented on src/app/modal/Stories.tsx
why submit a code with comments?

2023-05-31 09:25 UTC, kadjialan commented on src/assets/1.jpeg
i think a folder image will be better to contain the images

2023-05-31 12:48 UTC, kadjialan approved these changes

2023-05-31 12:49 UTC, closed without merging